openapi: 3.0.0
servers:
  - description: Staff Tracking Microservice
    url: http://localhost:<port>/api
info:
  description: This is the API of the Staff Tracking microservice within the Smart Operating Block project.
  version: "1.0.0"
  title: Staff Tracking API
  contact:
    email: info@smartoperatingblock.com
  license:
    name: MIT License
    url: 'https://opensource.org/license/mit/'

tags:
  - name: Health Professionals Tracking API
    description: This is the available API to obtain information about health professionals movements.
  - name: Room Tracking API
    description: This is the available API to obtain information about health professionals within an operating block room.
  - name: Block Tracking API
    description: This is the available API to obtain information about current health professionals within the operating block.

paths:

  /health-professionals-tracking/{healthProfessionalId}:
    get:
      tags:
        - Health Professionals Tracking API
      summary: Get the latest health professional tracking data by its Id
      operationId: getTHealthProfessionalrackingData
      description: Get Health Professional Tracking data
      parameters:
        - in: path
          name: healthProfessionalId
          description: the Health Professional ID
          required: true
          schema:
            type: string
        - in: query
          name: from
          required: false
          description: Specify a past date in order to obtain historical data. The date must be specified in the ISO 8601 UTC date format.
          schema:
            type: string
            format: date-time
            example: '2017-07-21T17:32:28Z'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfTrackingData'
        '204':
          description: No Content
        '500':
          description: server error occurred

  /room-tracking/{roomId}:
    get:
      tags:
        - Room Tracking API
      summary: Get the latest movements in a room given its id
      operationId: getRoomTrackingData
      description: Get Room Tracking data
      parameters:
        - in: path
          name: roomId
          description: the Room ID
          required: true
          schema:
            type: string
        - in: query
          name: from
          required: false
          description: Specify a past date in order to obtain historical data. The date must be specified in the ISO 8601 UTC date format.
          schema:
            type: string
            format: date-time
            example: '2017-07-21T17:32:28Z'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfTrackingData'
        '204':
          description: No Content
        '500':
          description: server error occurred

  /block-tracking-data/:
    get:
      tags:
        - Block Tracking API
      summary: Get the latest movements in the operating block
      operationId: getBlockTrackingData
      description: Get Block Tracking data
      parameters:
        - in: query
          name: from
          required: false
          description: Specify a past date in order to obtain historical data. The date must be specified in the ISO 8601 UTC date format.
          schema:
            type: string
            format: date-time
            example: '2017-07-21T17:32:28Z'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfTrackingData'
        '204':
          description: No Content
        '500':
          description: server error occurred
components:
  schemas:

    ArrayOfTrackingData:
      type: object
      properties:
        entries:
          type: array
          description: tracking data elements
          items:
            type: object
            properties:
              entry:
                $ref: '#/components/schemas/TrackingData'
        total:
          type: integer
          description: the total number of tracking data
          example: 34

    TrackingData:
      type: object
      properties:
        dateTime:
          type: string
        roomId:
          type: string
        healthProfessionalId:
          type: string
        trackingType:
          $ref: '#/components/schemas/TrackingType'

    TrackingType:
      type: string
      enum: [ENTER, EXIT]
      example: ENTER
